version: '3.9'

services:
  sqlserver:
    build:
      context: .
      dockerfile: DockerfileSqlServer
    container_name: sqlserver-container
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'YourStrong!Passw0rd'
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: